import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { z } from "zod/v4";

import { assembleFromSpec } from "../assembly/assemble";
import { siteSpecSchema, type SiteSpec } from "../assembly/site-spec";
import { computeManifest, type ArtifactManifest } from "../deploy/artifact";
import { deploy, PROJECT_ROOT, staging } from "../deploy/deploy";
import { previewHostname } from "../deploy/wrangler-config";
import { runFastGate } from "../qa/fast-gate";
import { resetGeneratedPages, restoreAssemblerOutputs, runFullSuite } from "../qa/run";
import { blockers } from "../qa/types";
import {
  advance,
  assertStage,
  carrierOf,
  changesDir,
  clientDir,
  DEFAULT_VAULT_ROOT,
  diffSpecs,
  listPassDirs,
  logEvent,
  nextCommand,
  openPassDir,
  PASS_FILES,
  passFolderName,
  readFrontmatter,
  readPass,
  renderDelta,
  sha256File,
  stateProposal,
  writePass,
  type Brief,
  type ChangeClass,
  type PassCarrier,
  type PassStage,
  type PassState,
} from "./pass";
import {
  abandonPass,
  bindPass,
  closePass,
  DEFAULT_PORTAL_BASE,
  getLiveSpec,
  getPasses,
  recordManualPass,
  seedDocument,
  type PortalOptions,
} from "./portal";
import {
  buildSite,
  diffAgainstLive,
  diffContent,
  dropBackup,
  materialiseSurface,
  pushLive,
  pushStaging,
  resolveSite,
  surfaceManifest,
  writeContent,
  templateDelta,
  validateSite,
  type AnnotatedSite,
} from "./annotated";

/**
 * The change-ticket runner — ticket 026's pass as a CLI.
 *
 *   npx tsx src/lib/change/run.ts <command> --slug <slug> [options]
 *
 * One command per stage, and each refuses to run out of order:
 *
 *   open      pull the live spec + the paid pass → changes/<ISO>/        → REVIEW
 *   review    write delta.md; `--approve` is the owner's gate            → BUILD
 *   build     assemble spec.json, `next build`                            → QA
 *   qa        fast gate always, full suite on major (009 §8)              → STAGING
 *   stage     deploy.ts STAGING on the built out/, overwrite the manifest → APPROVE
 *   approve   `--evidence` of the client's sign-off — the client's gate   → DEPLOY
 *   deploy    deploy.ts DEPLOY (no rebuild), then seed spec.json as live
 *
 * Ticket 031 adds a second carrier: when the live document is a hand-built site, BUILD, QA,
 * STAGING and DEPLOY run that site's own scripts instead (`annotated.ts`), and DEPLOY
 * rehearses unless `--live` — its target is a repo the client's DNS serves.
 *   close     close the pass in D1; the editor unlocks                   → CLOSED
 *
 * Plus `status`, `inbox` (every pass, unbound first), `bind` and `record`.
 *
 * What this deliberately does not do:
 *
 * - **Call `analysis/run.ts`.** 026 §0: it regenerates from intake and would wipe every
 *   post-launch self-edit. The live spec is the input. If a major ticket needs new copy,
 *   that is written into `spec.json` during REVIEW, not generated by a fresh ANALYSIS run.
 * - **Write `state.md`.** Propose-class. Every transition prints the diff and the Stage
 *   Log row; the owner pastes them.
 * - **Skip the seed.** DEPLOY puts the pass's bytes live, but post-launch the spec is
 *   cloud-owned (012 §6). Without the seed the client's next self-edit publish would
 *   rebuild from the pre-pass spec and silently revert the work they paid for — so
 *   `deploy` does not return success until the spec is seeded, and `close` refuses
 *   without a seeded version.
 *
 * `--dry-run` is a rehearsal: no wrangler, no portal, but the pass folder IS written so
 * the whole sequence can be walked. It therefore refuses the real Vault — rehearse with
 * `--vault-root <scratch dir>`.
 */

interface Flags {
  command: string;
  values: Record<string, string>;
  switches: Set<string>;
}

function parseArgs(argv: string[]): Flags {
  const [command = "", ...rest] = argv;
  const values: Record<string, string> = {};
  const switches = new Set<string>();
  for (let i = 0; i < rest.length; i++) {
    if (!rest[i].startsWith("--")) continue;
    const key = rest[i].slice(2);
    const next = rest[i + 1];
    if (next !== undefined && !next.startsWith("--")) {
      values[key] = next;
      i++;
    } else switches.add(key);
  }
  return { command, values, switches };
}

interface Context {
  flags: Flags;
  vaultRoot: string;
  dryRun: boolean;
  portal: PortalOptions;
}

function need(ctx: Context, name: string): string {
  const value = ctx.flags.values[name];
  if (!value) throw new Error(`--${name} is required for \`${ctx.flags.command}\``);
  return value;
}

function loadSpec(file: string): SiteSpec {
  const result = z.safeParse(siteSpecSchema, JSON.parse(fs.readFileSync(file, "utf-8")));
  if (!result.success) throw new Error(`${file} does not validate:\n${z.prettifyError(result.error)}`);
  return result.data;
}

function readJson<T>(file: string): T {
  return JSON.parse(fs.readFileSync(file, "utf-8")) as T;
}

function writeJson(file: string, value: unknown): void {
  fs.writeFileSync(file, JSON.stringify(value, null, 2) + "\n", "utf-8");
}

const TEMPLATE_BEFORE = "template.before.html";

/** The client site behind an annotated pass, as `open` pinned it. */
function siteOf(state: PassState): AnnotatedSite {
  if (!state.siteDir) throw new Error(`${state.slug} is an annotated pass with no site directory recorded.`);
  return resolveSite(state.siteDir);
}

function frontmatterOf(ctx: Context, slug: string): Record<string, string> {
  const file = path.join(clientDir(slug, ctx.vaultRoot), "state.md");
  if (!fs.existsSync(file)) throw new Error(`No client record at ${file}`);
  return readFrontmatter(fs.readFileSync(file, "utf-8"));
}

function requireOpenPass(ctx: Context, slug: string): { dir: string; state: PassState } {
  const dir = openPassDir(slug, ctx.vaultRoot);
  if (!dir) throw new Error(`${slug} has no open change pass. Start one with \`open\`.`);
  return { dir, state: readPass(dir) };
}

/** Writes the transition, then prints what `state.md` should say about it. */
function transition(
  ctx: Context,
  dir: string,
  state: PassState,
  to: PassStage,
  event: string,
  proposal?: { stage?: string; relationship?: string; substatus?: string },
): PassState {
  const next = advance(state, to, event);
  writePass(dir, next);
  console.log(`\n  pass → ${to}. Next: \`${nextCommand(to)}\``);
  if (proposal) {
    console.log(`\n${stateProposal(frontmatterOf(ctx, state.slug), proposal, event)}`);
  }
  return next;
}

function substatus(state: PassState, words: string): string {
  return `Change ticket (${state.klass} × ${state.quantity}) — ${words}`;
}

/** BUILD's tree, still there. A second session building into the same `out/` is real (SESSION-BRIEF §7). */
/**
 * The built tree, re-hashed and compared to what BUILD pinned — SESSION-BRIEF §7: one
 * Worker, one working tree. On the annotated carrier the tree is the surface materialised
 * into the pass folder, so the check takes the manifest rather than re-deriving `out/`.
 */
function assertPinnedTree(state: PassState, manifest: ArtifactManifest): ArtifactManifest {
  if (manifest.treeHash !== state.builtTreeHash) {
    throw new Error(
      `The built page is ${manifest.treeHash.slice(0, 12)}, not what BUILD left ` +
        `(${state.builtTreeHash?.slice(0, 12)}). Something rebuilt it since — run \`build\` again.`,
    );
  }
  return manifest;
}

function assertBuiltTree(state: PassState): ArtifactManifest {
  const current = computeManifest(path.join(PROJECT_ROOT, "out"), state.slug);
  if (current.treeHash !== state.builtTreeHash) {
    throw new Error(
      `out/ is not the tree BUILD produced (${state.builtTreeHash?.slice(0, 12) ?? "none"} → ` +
        `${current.treeHash.slice(0, 12)}). Something else built into this checkout. Run \`build\` again.`,
    );
  }
  return current;
}

/* ────────────────────────────────────────────────────────────────────────────
 * Commands
 * ──────────────────────────────────────────────────────────────────────────── */

async function open(ctx: Context): Promise<void> {
  const slug = need(ctx, "slug");
  const existing = openPassDir(slug, ctx.vaultRoot);
  if (existing) throw new Error(`${slug} already has an open pass: ${existing}`);

  const fm = frontmatterOf(ctx, slug);
  // The standing links are the productized rail and carry tasteled.com's terms; bespoke
  // change work is quoted per engagement, so it runs only when the owner says so per pass
  // (031 §1) — and then with no standing link and no guarantee copy behind it.
  const bespoke = ctx.flags.switches.has("bespoke");
  if (fm.tier !== "productized" && !bespoke) {
    throw new Error(
      `${slug} is tier "${fm.tier || "?"}". A change-ticket pass is productized by default — ` +
        `pass --bespoke to run one as quoted work (ticket 031 §1).`,
    );
  }
  // 026 §1: AethrDesign no longer holds the Worker or the zone.
  if (fm.relationship === "handed-over") throw new Error(`${slug} is handed-over — not ours to deploy.`);

  const domain = ctx.flags.values.domain ?? fm["cloudflare-zone"];
  if (!domain) throw new Error(`No apex for ${slug}: pass --domain (state.md \`cloudflare-zone\` is empty).`);
  const contactEmail = ctx.flags.values["contact-email"] ?? fm["contact-email"];
  if (!contactEmail) throw new Error(`No contact email for ${slug}: pass --contact-email.`);

  let passId: string | null = null;
  let paymentRef: string | null = null;
  let klass = ctx.flags.values.class as ChangeClass | undefined;
  let quantity = Number(ctx.flags.values.quantity ?? 1);
  let before: unknown;
  let baseVersion: number | null = null;
  const brief: Brief = { requests: [], dirtyDraft: null };

  let carrier: PassCarrier = "spec";

  if (ctx.portal.offline) {
    before = readJson(need(ctx, "spec-file"));
    carrier = (ctx.flags.values.carrier as PassCarrier | undefined) ?? "spec";
    if (!klass) throw new Error("--class minor|major is required offline.");
    console.log(`  [offline] live spec from ${ctx.flags.values["spec-file"]}; no pass in D1`);
  } else {
    // Payment first. The pass exists because money did — there is no open without one.
    const { passes, requests = [] } = await getPasses(ctx.portal, slug);
    const paid = passes.filter((p) => p.status === "paid");
    const pass = ctx.flags.values.pass ? paid.find((p) => p.id === ctx.flags.values.pass) : paid[0];
    if (!pass) {
      throw new Error(
        `No paid change pass in D1 for ${slug}.\n` +
          `  bare-link payment → \`inbox\`, then \`bind --pass <id> --slug ${slug}\`\n` +
          `  another rail      → \`record --slug ${slug} --class … --amount-cents … --payment-ref …\``,
      );
    }
    passId = pass.id;
    paymentRef = pass.payment_ref;
    klass = pass.klass ?? klass;
    if (!klass) throw new Error(`Pass ${pass.id} has no class (unit amount matched no link) — pass --class.`);
    quantity = pass.quantity;
    brief.requests = requests.filter((r) => r.pass_id === pass.id || r.status === "open");

    const live = await getLiveSpec(ctx.portal, slug);
    // 031 §2: the carrier is the live document's, never a flag. A hand-built site's
    // stages run the scripts in the client's own folder; everything above BUILD is shared.
    carrier = live.kind === "annotated" ? "annotated" : "spec";
    before = live.spec;
    baseVersion = live.version;
    if (live.draft && live.draft.kind === live.kind) {
      const delta =
        carrier === "annotated"
          ? diffContent(live.spec, live.draft.spec)
          : diffSpecs(live.spec, live.draft.spec);
      if (delta.length) {
        brief.dirtyDraft = { baseVersion: live.draft.baseVersion, updatedAt: live.draft.updatedAt, delta };
      }
    }
  }

  // The scripts, the markup and the live checkout all live in the client's folder.
  const site = carrier === "annotated" ? resolveSite(need(ctx, "site-dir")) : null;

  const beforeDocument = carrier === "spec" ? siteSpecSchema.parse(before) : before;
  const dir = path.join(changesDir(slug, ctx.vaultRoot), passFolderName(new Date()));
  fs.mkdirSync(dir, { recursive: true });
  writeJson(path.join(dir, PASS_FILES.before), beforeDocument);
  writeJson(path.join(dir, PASS_FILES.spec), beforeDocument);
  writeJson(path.join(dir, PASS_FILES.brief), brief);
  // The markup as the pass found it. A template edit is the paid side of this carrier
  // (031 §2), and without a copy here REVIEW has nothing to diff it against.
  if (site) fs.copyFileSync(path.join(site.mockup, "template.html"), path.join(dir, TEMPLATE_BEFORE));

  const state: PassState = {
    slug,
    carrier,
    ...(site ? { siteDir: site.root } : {}),
    ...(ctx.flags.values["asset-base"] ? { assetBase: ctx.flags.values["asset-base"] } : {}),
    ...(bespoke ? { bespoke: true } : {}),
    passId,
    paymentRef,
    klass,
    quantity,
    contactEmail,
    domain,
    openedAt: new Date().toISOString(),
    baseVersion,
    stage: "REVIEW",
    log: [],
  };
  fs.writeFileSync(path.join(dir, PASS_FILES.delta), renderDelta(state, [], brief), "utf-8");

  console.log(
    `OPEN ${slug} — ${klass} × ${quantity}, from live v${baseVersion ?? "?"}` +
      (carrier === "annotated" ? " (hand-built site)" : ""),
  );
  console.log(`  ${dir}`);
  if (brief.requests.length) console.log(`  ${brief.requests.length} request(s) in delta.md`);
  if (brief.dirtyDraft) console.log(`  ! the client has an unpublished draft — see delta.md before approving`);
  console.log(
    `\n  Edit ${path.join(dir, PASS_FILES.spec)} — paid paths only, against the live ` +
      `${carrier === "annotated" ? "content" : "spec"}.`,
  );
  if (site) console.log(`  Markup edits go in ${path.join(site.mockup, "template.html")} — that is the paid side here.`);

  transition(ctx, dir, state, "REVIEW", "change pass opened", {
    stage: "REVIEW",
    relationship: "active",
    substatus: substatus(state, "in review"),
  });
}

function review(ctx: Context): void {
  const slug = need(ctx, "slug");
  const { dir, state } = requireOpenPass(ctx, slug);
  assertStage(state, "review");

  const specFile = path.join(dir, PASS_FILES.spec);
  const before = readJson<unknown>(path.join(dir, PASS_FILES.before));
  const brief = readJson<Brief>(path.join(dir, PASS_FILES.brief));

  let delta: ReturnType<typeof diffSpecs>;
  if (carrierOf(state) === "annotated") {
    const site = siteOf(state);
    delta = diffContent(before, readJson<unknown>(specFile));
    // The markup is the paid side of this carrier, and it is edited in place rather than
    // in the pass folder — so REVIEW reads it off disk against the copy `open` pinned.
    delta = [
      ...templateDelta(
        fs.readFileSync(path.join(dir, TEMPLATE_BEFORE), "utf-8"),
        fs.readFileSync(path.join(site.mockup, "template.html"), "utf-8"),
      ),
      ...delta,
    ];
  } else {
    delta = diffSpecs(before, loadSpec(specFile));
  }
  fs.writeFileSync(path.join(dir, PASS_FILES.delta), renderDelta(state, delta, brief), "utf-8");

  const paid = delta.filter((d) => !d.free).length;
  console.log(`REVIEW ${slug} — ${delta.length} change(s), ${paid} on paid paths`);
  console.log(`  ${path.join(dir, PASS_FILES.delta)}`);

  if (!ctx.flags.switches.has("approve")) {
    console.log("\n  Read delta.md, then `review --approve` to pass the owner's gate.");
    return;
  }
  if (delta.length === 0) throw new Error("spec.json equals the live spec — there is nothing to approve.");

  // Approving again after a build resets the build: the reviewed bytes changed.
  const next: PassState = {
    ...state,
    reviewedSpecHash: sha256File(specFile),
    builtTreeHash: undefined,
  };
  transition(ctx, dir, next, "BUILD", `REVIEW approved — ${delta.length} change(s), ${paid} paid`, {
    stage: "BUILD",
    substatus: substatus(state, "building"),
  });
}

async function build(ctx: Context): Promise<void> {
  const slug = need(ctx, "slug");
  const { dir, state } = requireOpenPass(ctx, slug);
  assertStage(state, "build");

  const specFile = path.join(dir, PASS_FILES.spec);
  if (sha256File(specFile) !== state.reviewedSpecHash) {
    throw new Error("spec.json changed since REVIEW approved it. Run `review --approve` again.");
  }

  console.log(`BUILD ${slug}`);

  if (carrierOf(state) === "annotated") {
    const site = siteOf(state);
    // The mirror is restored only if the build throws: past this point the client's words
    // are what the site is built from, and `close` is what puts the mirror back in step.
    const restore = writeContent(site, readJson<unknown>(specFile));
    try {
      buildSite(site);
    } catch (err) {
      restore();
      throw err;
    }
    dropBackup(site);
    const built = surfaceManifest(site, dir, slug);
    console.log(`  built ${built.treeHash.slice(0, 12)} — ${built.fileCount} files`);
    transition(ctx, dir, { ...state, builtTreeHash: built.treeHash }, "QA", `built ${built.treeHash.slice(0, 12)}`);
    return;
  }

  // Same order as `qa/run.ts`: a page left by a previous client's spec must not ride along.
  resetGeneratedPages(PROJECT_ROOT);
  try {
    await assembleFromSpec(specFile, PROJECT_ROOT);
    // `npx next build`, as `deploy.ts` and the cloud builder run it — the paths cannot diverge.
    execFileSync("npx", ["next", "build"], { cwd: PROJECT_ROOT, stdio: "inherit" });
  } finally {
    // `out/` is built; the sources going back cannot change a byte of it.
    resetGeneratedPages(PROJECT_ROOT);
    restoreAssemblerOutputs(PROJECT_ROOT);
  }

  const manifest = computeManifest(path.join(PROJECT_ROOT, "out"), slug);
  console.log(`  built ${manifest.treeHash.slice(0, 12)} — ${manifest.fileCount} files`);
  transition(ctx, dir, { ...state, builtTreeHash: manifest.treeHash }, "QA", `built ${manifest.treeHash.slice(0, 12)}`);
}

async function qa(ctx: Context): Promise<void> {
  const slug = need(ctx, "slug");
  const { dir, state } = requireOpenPass(ctx, slug);
  assertStage(state, "qa");
  if (carrierOf(state) !== "annotated") assertBuiltTree(state);

  const specFile = path.join(dir, PASS_FILES.spec);
  const qaDir = path.join(dir, PASS_FILES.qa);
  fs.mkdirSync(qaDir, { recursive: true });

  if (carrierOf(state) === "annotated") {
    assertPinnedTree(state, surfaceManifest(siteOf(state), dir, slug));
    // One gate, and it is the client's own: `validate.mjs` is what both deploy scripts
    // refuse on, so a pass that passes here is a pass the site's own deploy would accept.
    console.log(`QA ${slug} — edit-layer contract`);
    const result = validateSite(siteOf(state));
    fs.writeFileSync(path.join(qaDir, "edit-layer.txt"), `${result.output}\n`, "utf-8");
    if (!result.ok) {
      console.error(result.output);
      writePass(dir, logEvent(state, "QA failed — the edit-layer contract is broken"));
      throw new Error("QA failed: the edit-layer contract is broken. Fix the content or the markup, then rebuild.");
    }
    transition(ctx, dir, state, "STAGING", "QA passed — edit-layer contract");
    return;
  }

  const spec = loadSpec(specFile);
  console.log(`QA ${slug} — fast gate${state.klass === "major" ? " + full suite (major)" : ""}`);
  const gate = await runFastGate({ spec, projectRoot: PROJECT_ROOT });
  writeJson(path.join(qaDir, "fast-gate.json"), gate);
  const failures = [...gate.findings];

  // 009 §8, as 026 carried it: the class splits the QA suite, not the path.
  if (state.klass === "major") {
    const suite = await runFullSuite({
      specPath: specFile,
      projectRoot: PROJECT_ROOT,
      outDir: qaDir,
      check: "all",
      skipAssemble: true,
      skipBuild: true,
    });
    failures.push(...blockers(suite));
  }

  if (failures.length) {
    for (const f of failures) console.error(`  ${f.check}: ${f.message}`);
    writePass(dir, logEvent(state, `QA failed — ${failures.length} blocker(s)`));
    throw new Error(`QA failed with ${failures.length} blocker(s). Fix spec.json, re-approve REVIEW, rebuild.`);
  }
  transition(ctx, dir, state, "STAGING", `QA passed${gate.advisories.length ? ` (${gate.advisories.length} advisory)` : ""}`);
}

async function stage(ctx: Context): Promise<void> {
  const slug = need(ctx, "slug");
  const { dir, state } = requireOpenPass(ctx, slug);
  assertStage(state, "stage");
  if (carrierOf(state) !== "annotated") assertBuiltTree(state);

  if (carrierOf(state) === "annotated") {
    const site = siteOf(state);
    // The script validates and rebuilds on its own before it pushes. Re-materialising the
    // surface first is the same drift check the assembled carrier gets from `out/`: a tree
    // another session rebuilt must not be the one the client is asked to approve.
    const manifest = assertPinnedTree(state, surfaceManifest(site, dir, slug));
    if (ctx.dryRun) console.log(`  [dry-run] would run ${path.basename(site.stagingScript)}`);
    else pushStaging(site);
    writeJson(path.join(clientDir(slug, ctx.vaultRoot), "approved-artifact.json"), manifest);
    writeJson(path.join(dir, PASS_FILES.artifact), manifest);
    console.log(
      `\n  Send the client the staging URL ${path.basename(site.stagingScript)} just printed, for APPROVE.` +
        // 031 §1: a bespoke engagement never had the guarantee, so its APPROVE must not
        // mention one in either direction.
        (state.bespoke ? "" : "\n  The money-back guarantee is CLOSED on this approval (006, 026 §1 step 6)."),
    );
    transition(
      ctx,
      dir,
      { ...state, stagedTreeHash: manifest.treeHash },
      "APPROVE",
      `staged ${manifest.treeHash.slice(0, 12)}`,
      { stage: "APPROVE", substatus: substatus(state, "ready for your approval") },
    );
    return;
  }

  // 026 §1 step 5: a new out/, and the SAME manifest file STAGING always writes, overwritten.
  // Re-binding a retired preview host needs nothing special — staging always attaches it.
  const manifest = await staging({
    slug,
    contactEmail: state.contactEmail,
    domain: state.domain,
    vaultRoot: ctx.vaultRoot,
    skipBuild: true,
    dryRun: ctx.dryRun,
  });
  if (ctx.dryRun) {
    // staging() writes nothing in dry-run; a rehearsal still needs DEPLOY's drift check to bite.
    writeJson(path.join(clientDir(slug, ctx.vaultRoot), "approved-artifact.json"), manifest);
  }
  writeJson(path.join(dir, PASS_FILES.artifact), manifest);

  console.log(
    `\n  Send the client https://${previewHostname(slug)} for APPROVE.\n` +
      `  The money-back guarantee is CLOSED on this approval (006, 026 §1 step 6) — ` +
      `nothing sent with it may say money back.`,
  );
  transition(ctx, dir, { ...state, stagedTreeHash: manifest.treeHash }, "APPROVE", `staged ${manifest.treeHash.slice(0, 12)}`, {
    stage: "APPROVE",
    substatus: substatus(state, "ready for your approval"),
  });
}

function approve(ctx: Context): void {
  const slug = need(ctx, "slug");
  const { dir, state } = requireOpenPass(ctx, slug);
  assertStage(state, "approve");
  const evidence = need(ctx, "evidence");

  const pinned = readJson<ArtifactManifest>(path.join(clientDir(slug, ctx.vaultRoot), "approved-artifact.json"));
  if (pinned.treeHash !== state.stagedTreeHash) {
    throw new Error(
      `approved-artifact.json (${pinned.treeHash.slice(0, 12)}) is not what this pass staged ` +
        `(${state.stagedTreeHash?.slice(0, 12)}). Something re-staged ${slug} since. Do not record an approval for it.`,
    );
  }
  transition(ctx, dir, { ...state, approval: evidence }, "DEPLOY", `client approved — ${evidence}`, {
    stage: "DEPLOY",
    substatus: substatus(state, "going live"),
  });
}

async function deployCmd(ctx: Context): Promise<void> {
  const slug = need(ctx, "slug");
  const { dir } = requireOpenPass(ctx, slug);
  let state = readPass(dir);
  assertStage(state, "deploy");
  if (state.seededVersion !== undefined) throw new Error("Already deployed and seeded — run `close`.");

  if (carrierOf(state) === "annotated") {
    await deployAnnotated(ctx, dir, state);
    return;
  }

  if (!state.deployedAt) {
    await deploy({
      slug,
      contactEmail: state.contactEmail,
      domain: state.domain,
      vaultRoot: ctx.vaultRoot,
      dryRun: ctx.dryRun,
    });
    state = logEvent({ ...state, deployedAt: new Date().toISOString() }, `deployed to ${state.domain}`);
    // Recorded before the seed, so a failed seed re-runs only the seed.
    writePass(dir, state);
  } else {
    console.log(`  deployed ${state.deployedAt} — retrying the spec seed only`);
  }

  const spec = loadSpec(path.join(dir, PASS_FILES.spec));
  const version = await seedDocument(
    ctx.portal,
    slug,
    { kind: "spec", spec },
    `change ticket ${state.passId ?? "offline"}`,
  );
  state = logEvent({ ...state, seededVersion: version }, `spec seeded as v${version}`);
  writePass(dir, state);
  console.log(`  spec seeded as live v${version}. Next: \`close\``);
}

/**
 * DEPLOY on the annotated carrier — ticket 031 §3.
 *
 * The target is a repository the client's DNS serves, not infrastructure AethrDesign
 * holds, so this rehearses unless the owner passes `--live`: it checks the built surface
 * is still the approved one, reports what `deploy-live.sh` would change, and stops. The
 * seed runs only on a real push, because a live version the site does not serve would make
 * the portal's `liveVersion` — and the client's History — lie.
 */
async function deployAnnotated(ctx: Context, dir: string, state: PassState): Promise<void> {
  const site = siteOf(state);
  const surface = materialiseSurface(site, dir);
  const manifest = surfaceManifest(site, dir, state.slug);
  if (manifest.treeHash !== state.stagedTreeHash) {
    throw new Error(
      `The built page (${manifest.treeHash.slice(0, 12)}) is not what the client approved ` +
        `(${state.stagedTreeHash?.slice(0, 12)}). Re-stage before deploying.`,
    );
  }

  const diff = diffAgainstLive(site, surface);
  const total = diff.changed.length + diff.added.length + diff.removed.length;
  if (diff.cloneMissing) {
    console.log(`  no live checkout on disk — ${path.basename(site.liveScript)} would clone it first`);
  } else {
    console.log(`  against live: ${diff.changed.length} changed, ${diff.added.length} added, ${diff.removed.length} removed`);
    for (const rel of [...diff.changed, ...diff.added, ...diff.removed].slice(0, 12)) console.log(`    ${rel}`);
  }

  if (!ctx.flags.switches.has("live")) {
    const at = new Date().toISOString();
    const next = logEvent(
      { ...state, rehearsedAt: at },
      `DEPLOY rehearsed against ${state.domain} — ${total} file(s) would change, nothing pushed`,
    );
    writePass(dir, next);
    console.log(
      `\n  REHEARSED — nothing was pushed to ${state.domain} and no version was seeded.\n` +
        `  Pass --live to run ${path.basename(site.liveScript)} for real, or \`close\` to end the pass here.`,
    );
    return;
  }

  if (ctx.dryRun) console.log(`  [dry-run] would run ${path.basename(site.liveScript)}`);
  else pushLive(site);
  let next = logEvent({ ...state, deployedAt: new Date().toISOString() }, `deployed live to ${state.domain}`);
  writePass(dir, next);

  const version = await seedDocument(
    ctx.portal,
    state.slug,
    {
      kind: "annotated",
      content: readJson<unknown>(path.join(dir, PASS_FILES.spec)),
      template: fs.readFileSync(path.join(site.mockup, "template.html"), "utf-8"),
      assetBase: state.assetBase,
    },
    `change ticket ${state.passId ?? "offline"}`,
  );
  next = logEvent({ ...next, seededVersion: version }, `content seeded as v${version}`);
  writePass(dir, next);
  console.log(`  content seeded as live v${version}. Next: \`close\``);
}

async function close(ctx: Context): Promise<void> {
  const slug = need(ctx, "slug");
  const { dir, state } = requireOpenPass(ctx, slug);
  assertStage(state, "close");

  // 031 §3: a rehearsed DEPLOY has no seeded version, and closing it against one would
  // claim a version the live site does not serve. It ends as abandoned instead — the
  // editor still unlocks, and the requests it was paying for go back to open.
  const rehearsed = state.seededVersion === undefined;
  if (state.passId) {
    if (rehearsed) await abandonPass(ctx.portal, state.passId, `DEPLOY rehearsed ${state.rehearsedAt}, never pushed`);
    else await closePass(ctx.portal, state.passId, state.seededVersion as number);
  } else console.log("  offline pass — nothing to close in D1");

  transition(
    ctx,
    dir,
    state,
    "CLOSED",
    rehearsed
      ? `pass abandoned — DEPLOY rehearsed ${state.rehearsedAt}, nothing pushed; editor unlocked`
      : `pass closed at v${state.seededVersion}; editor unlocked`,
    {
      stage: "DEPLOY",
      relationship: "dormant",
      substatus: rehearsed ? substatus(state, "rehearsed, not shipped") : "Live",
    },
  );
}

function status(ctx: Context): void {
  const slug = need(ctx, "slug");
  const dirs = listPassDirs(slug, ctx.vaultRoot);
  if (!dirs.length) {
    console.log(`${slug}: no change passes.`);
    return;
  }
  for (const dir of dirs) {
    const s = readPass(dir);
    console.log(`${path.basename(dir)}  ${s.stage.padEnd(8)} ${s.klass} × ${s.quantity}  pass ${s.passId ?? "offline"}`);
    if (s.stage !== "CLOSED") {
      for (const entry of s.log.slice(-5)) console.log(`    ${entry.at}  ${entry.stage.padEnd(8)} ${entry.event}`);
      console.log(`    next: \`${nextCommand(s.stage)}\``);
    }
  }
}

async function inbox(ctx: Context): Promise<void> {
  const { passes } = await getPasses(ctx.portal, ctx.flags.values.slug);
  if (!passes.length) {
    console.log("No change passes.");
    return;
  }
  for (const p of passes) {
    const who = p.slug ?? `UNBOUND (reference: ${p.client_reference ?? "none"})`;
    console.log(
      `${p.id}  ${p.status.padEnd(6)} ${who}  ${p.klass ?? "?"} × ${p.quantity}  ` +
        `$${(p.amount_cents / 100).toFixed(2)} ${p.currency}  ${p.paid_at}  ${p.customer_email ?? ""}`,
    );
  }
}

async function bind(ctx: Context): Promise<void> {
  const pass = await bindPass(ctx.portal, need(ctx, "pass"), need(ctx, "slug"));
  console.log(`bound ${pass.id} → ${pass.slug}. The editor is now read-only for them.`);
}

async function record(ctx: Context): Promise<void> {
  const klass = need(ctx, "class");
  if (klass !== "minor" && klass !== "major") throw new Error("--class must be minor or major");
  const pass = await recordManualPass(ctx.portal, {
    slug: need(ctx, "slug"),
    klass,
    quantity: Number(ctx.flags.values.quantity ?? 1),
    amountCents: Number(need(ctx, "amount-cents")),
    paymentRef: need(ctx, "payment-ref"),
  });
  console.log(`recorded ${pass.id} for ${pass.slug}. Next: \`open --slug ${pass.slug}\``);
}

const COMMANDS: Record<string, (ctx: Context) => void | Promise<void>> = {
  open,
  review,
  build,
  qa,
  stage,
  approve,
  deploy: deployCmd,
  close,
  status,
  inbox,
  bind,
  record,
};

const USAGE = `Usage: npx tsx src/lib/change/run.ts <command> [options]

  open     --slug <s> [--pass <id>] [--domain <apex>] [--contact-email <addr>]
           [--bespoke]                 quoted work on a non-productized client (031 §1)
           [--site-dir <path>]         required when the live document is a hand-built site
           [--asset-base <url>]        where that site's relative assets/ are served from
  review   --slug <s> [--approve]
  build    --slug <s>
  qa       --slug <s>
  stage    --slug <s>
  approve  --slug <s> --evidence "<how the client signed off>"
  deploy   --slug <s> [--live]        annotated: rehearses unless --live (031 §3)
  close    --slug <s>
  status   --slug <s>
  inbox    [--slug <s>]
  bind     --pass <id> --slug <s>
  record   --slug <s> --class minor|major --amount-cents <n> --payment-ref <ref> [--quantity <n>]

Global:  --vault-root <path>   default ${DEFAULT_VAULT_ROOT}
         --portal-base <url>   default ${DEFAULT_PORTAL_BASE}
         --offline             no portal calls; \`open\` then needs --spec-file and --class
                               (and --carrier annotated for a hand-built site)
         --dry-run             rehearsal: no wrangler, no portal; refuses the real Vault

Portal calls need INTAKE_ADMIN_SECRET, and CF_ACCESS_CLIENT_ID / CF_ACCESS_CLIENT_SECRET
(an Access service token) against portal.aethrdesign.com.
`;

async function main(): Promise<void> {
  const flags = parseArgs(process.argv.slice(2));
  const handler = COMMANDS[flags.command];
  if (!handler) {
    console.log(USAGE);
    process.exit(flags.command ? 1 : 0);
  }

  const vaultRoot = path.resolve(flags.values["vault-root"] ?? DEFAULT_VAULT_ROOT);
  const dryRun = flags.switches.has("dry-run");
  if (dryRun && vaultRoot === path.resolve(DEFAULT_VAULT_ROOT)) {
    throw new Error("--dry-run writes pass state as it rehearses — point it at a scratch --vault-root.");
  }
  const ctx: Context = {
    flags,
    vaultRoot,
    dryRun,
    portal: {
      base: flags.values["portal-base"] ?? DEFAULT_PORTAL_BASE,
      offline: dryRun || flags.switches.has("offline"),
    },
  };
  await handler(ctx);
}

if (process.argv[1]?.replace(/\\/g, "/").includes("change/run")) {
  main().catch((err: unknown) => {
    console.error(`\n${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(1);
  });
}
